#theme: jekyll-theme-slate
title: TypeScript+React Primer
description: "Hello & Welcome"
google_analytics: UA-52532512-4
show_downloads: false
# Root folder of the site, no trailing slash (empty when using custom domain)
# Other pages and _includes can refer to this setting as {{ site.baseurl }}
baseurl: ""